# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o ./bin/dir-md-toc .
      
    - name: Generate Toc
      run: ./bin/dir-md-toc -dir ./example -out ./example
      
    - name: Commit build
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
          git config --global user.name "linabellbiu"
          git config --global user.email "coke10086@gmail.com"
          git add .
          git commit -m 'Update build' || true
          git push    
